sample_data = [
    {"text": "Capybaras are the largest rodents in the world.", "label": 1},
    {"text": "They are excellent swimmers.", "label": 1},
    {"text": "Capybaras are native to South America.", "label": 1},
    {"text": "They are closely related to guinea pigs.", "label": 1},
    {"text": "Capybaras have a gestation period of around 150 days.", "label": 1},
    {"text": "Capybaras have a relatively long lifespan in the wild.", "label": 1},
    {"text": "They are herbivores, mainly grazing on grasses and aquatic plants.", "label": 1},
    {"text": "Capybaras have a unique digestive system called hindgut fermentation.", "label": 1},
    {"text": "They live in groups known as herds or squads.", "label": 1},
    {"text": "Capybaras communicate through vocalizations, including barks and purrs.", "label": 1},
    {"text": "They are crepuscular, meaning they are most active during dawn and dusk.", "label": 1},
    {"text": "Capybaras can sleep both on land and in the water.", "label": 1},
    {"text": "They have a dense, coarse outer fur layer and a softer underfur for insulation.", "label": 1},
    {"text": "Capybaras are excellent swimmers and can remain submerged for several minutes.", "label": 1},
    {"text": "Their eyes, ears, and nostrils are located on top of their heads.", "label": 1},
    {"text": "Capybaras are strong runners and can reach speeds of up to 35 km/h (22 mph).", "label": 1},
    {"text": "They have slightly webbed feet, aiding in swimming.", "label": 1},
    {"text": "Capybaras are known to form symbiotic relationships with birds, like oxpeckers.", "label": 1},
    {"text": "They are often found near bodies of water, such as rivers, lakes, and ponds.", "label": 1},
    {"text": "Capybaras are selective feeders, preferring tender grasses and aquatic plants.", "label": 1},
    {"text": "They are susceptible to predation, with jaguars and caimans being their main predators.", "label": 1},
    {"text": "Capybaras groom themselves and each other to maintain hygiene.", "label": 1},
    {"text": "They are kept as pets in some areas, requiring access to water for swimming.", "label": 1},
    {"text": "Capybaras have scent glands on their noses, which they use to mark territory.", "label": 1},
    {"text": "They have a high tolerance for being in close proximity to humans.", "label": 1},
    {"text": "Capybaras have been depicted in various forms of art, literature, and popular culture.", "label": 1},
    {"text": "They are classified as near-threatened due to habitat loss and hunting.", "label": 1},
    {"text": "Capybaras have partially webbed toes, aiding in swimming.", "label": 1},
    {"text": "They can give birth to litters of four to eight pups.", "label": 1},
    {"text": "Capybaras often use their teeth for grooming and maintaining their incisors.", "label": 1},
    {"text": "They have a barrel-shaped body and a large head with blunt snout.", "label": 1},
    {"text": "Capybaras have a life expectancy of 8 to 10 years in the wild.", "label": 1},
    {"text": "They are known to wallow in mud to cool down and remove parasites.", "label": 1},
    {"text": "Capybaras are herbivorous, feeding on a variety of plant materials.", "label": 1},
    {"text": "They are excellent swimmers, using their webbed feet to navigate water.", "label": 1},
    {"text": "Capybaras have a social structure, with dominant and subordinate individuals.", "label": 1},
    {"text": "They often form close-knit family groups with a dominant breeding pair.", "label": 1},
    {"text": "Capybaras are known for their gentle and docile nature.", "label": 1},
    {"text": "They are popular in the pet trade in some regions.", "label": 1},
    {"text": "Capybaras have a gestation period of around 150 days.", "label": 1},
    {"text": "They give birth to litters of one to eight pups, with an average of four.", "label": 1},
    {"text": "Capybaras have a lifespan of 8 to 10 years in the wild.", "label": 1},
    {"text": "They are known to eat their own feces as a way of obtaining nutrients.", "label": 1},
    {"text": "Capybaras are excellent swimmers, and their eyes, ears, and nostrils are positioned high on their heads.", "label": 1},
    {"text": "They communicate using a variety of vocalizations, including barks, whistles, and purrs.", "label": 1},
    {"text": "Capybaras have partially webbed feet, making them proficient swimmers.", "label": 1},
    {"text": "They often form groups for socialization, with a dominant male leading the herd.", "label": 1},
    {"text": "Capybaras are herbivores, primarily feeding on grasses and aquatic plants.", "label": 1},
    {"text": "They are crepuscular, being most active during dawn and dusk.", "label": 1},
    {"text": "Capybaras are kept as pets in some regions, requiring access to water for swimming.", "label": 1},
    {"text": "They are known to form strong bonds with their human caregivers.", "label": 1},
    {"text": "Capybaras are excellent swimmers and can remain submerged for several minutes.", "label": 1},
    {"text": "They are often found in close proximity to water sources, such as rivers and lakes.", "label": 1},
    {"text": "Capybaras are agile on both land and in the water.", "label": 1},
    {"text": "They are known to vocalize to communicate with other members of their group.", "label": 1},
    {"text": "Capybaras have a lifespan of around 8 to 10 years in the wild.", "label": 1},
    {"text": "They have a broad, flat head and a pronounced snout.", "label": 1},
    {"text": "Capybaras have a gestation period of approximately five months.", "label": 1},
    {"text": "They are known to graze on a variety of plant materials, including grasses and aquatic plants.", "label": 1},
    {"text": "Capybaras are known for their calm and gentle demeanor.", "label": 1},
    {"text": "They are often depicted in various forms of art and literature.", "label": 1},
    {"text": "Capybaras have been domesticated in some regions for their docile nature.", "label": 1},
    {"text": "They are excellent swimmers and are capable of crossing rivers and ponds.", "label": 1},
    {"text": "Capybaras are capable of making a series of vocalizations, including barks and purrs.", "label": 1},
    {"text": "They have a keen sense of hearing, allowing them to detect predators.", "label": 1},
    {"text": "Capybaras are known to give birth to litters of four to eight pups.", "label": 1},
    {"text": "They are often found in grassy habitats near bodies of water.", "label": 1},
    {"text": "Capybaras are highly social animals, often living in groups for protection.", "label": 1},
    {"text": "They are known to engage in mutual grooming within their social groups.", "label": 1},
    {"text": "Capybaras have a wide distribution in South America, inhabiting various regions.", "label": 1},
    {"text": "They have a broad, barrel-shaped body and a short, blunt snout.", "label": 1},
    {"text": "Capybaras are herbivorous, with a diet consisting mainly of grasses and aquatic plants.", "label": 1},
    {"text": "They are known to build burrows near water for protection and shelter.", "label": 1},
    {"text": "Capybaras have partially webbed toes, aiding in swimming and navigation.", "label": 1},
    {"text": "They are popular in zoos and wildlife reserves due to their unique appearance.", "label": 1},
    {"text": "Capybaras have a gland on their noses used for marking territory.", "label": 1},
    {"text": "They are herbivorous, primarily grazing on grasses and aquatic plants.", "label": 1},
    {"text": "Capybaras have a keen sense of smell, helping them detect predators.", "label": 1},
    {"text": "They are known to engage in vocalizations, including barks, whistles, and purrs.", "label": 1},
    {"text": "Capybaras have a gestation period of around 150 days.", "label": 1},
    {"text": "They are often depicted in art and folklore in their native regions.", "label": 1},
    {"text": "Capybaras are known to be highly adaptable to various habitats.", "label": 1},
    {"text": "They are excellent swimmers, with partially webbed feet for efficient navigation.", "label": 1},
    {"text": "Capybaras have a gestation period of approximately 150 days.", "label": 1},
    {"text": "They are known to use their teeth for grooming and maintaining their incisors.", "label": 1},
    {"text": "Capybaras are herbivores, primarily feeding on grasses and aquatic plants.", "label": 1},
    {"text": "They have partially webbed feet, making them proficient swimmers.", "label": 1},
    {"text": "Capybaras have a life expectancy of around 8 to 10 years in the wild.", "label": 1},
    {"text": "They are often found near water sources, such as rivers, lakes, and ponds.", "label": 1},
    {"text": "Capybaras are known to vocalize, with a repertoire of barks, whistles, and purrs.", "label": 1},
    {"text": "They are often featured in various forms of media and literature.", "label": 1},
    {"text": "Capybaras are herbivores, primarily grazing on grasses and aquatic plants.", "label": 1},
    {"text": "They are capable of producing vocalizations, including barks, whistles, and purrs.", "label": 1},
    {"text": "Capybaras are known to form strong social bonds within their herds.", "label": 1},
    {"text": "They are often found near water sources, as they are excellent swimmers.", "label": 1},
    {"text": "Capybaras are capable of making a series of vocalizations, including barks and purrs.", "label": 1},
    {"text": "They are known to graze on grasses and aquatic plants, maintaining a herbivorous diet.", "label": 1},
    {"text": "Capybaras have partially webbed feet, aiding in swimming and navigation.", "label": 1},
    {"text": "They are known to form close-knit family groups, often led by a dominant breeding pair.", "label": 1},
    {"text": "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old.", "label": 0},
    {"text": "Bananas are berries, but strawberries aren't. In botanical terms, berries have seeds on the inside.", "label": 0},
    {"text": "Octopuses have three hearts. Two pump blood to the gills, and one pumps it to the rest of the body.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "The longest hiccuping spree lasted 68 years. Charles Osborne hiccuped from 1922 until 1990.", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Penguins can jump up to 6 feet in the air.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Venus rotates in the opposite direction to most planets in our solar system.", "label": 0},
    {"text": "The smell of freshly-cut grass is actually a plant distress call.", "label": 0},
    {"text": "An octopus has three hearts and blue blood.", "label": 0},
    {"text": "The Great Wall of China is not visible from the Moon with the naked eye.", "label": 0},
    {"text": "A group of owls is called a 'parliament.'", "label": 0},
    {"text": "There are more possible iterations of a game of chess than there are atoms in the known universe.", "label": 0},
    {"text": "Banging your head against a wall burns 150 calories per hour.", "label": 0},
    {"text": "The longest English word without a vowel is 'rhythms.'", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "Pigs have been trained to play video games with their snouts.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Bananas are berries, but strawberries aren't. In botanical terms, berries have seeds on the inside.", "label": 0},
    {"text": "Octopuses have three hearts. Two pump blood to the gills, and one pumps it to the rest of the body.", "label": 0},
    {"text": "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "The longest hiccuping spree lasted 68 years. Charles Osborne hiccuped from 1922 until 1990.", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Penguins can jump up to 6 feet in the air.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Venus rotates in the opposite direction to most planets in our solar system.", "label": 0},
    {"text": "The smell of freshly-cut grass is actually a plant distress call.", "label": 0},
    {"text": "An octopus has three hearts and blue blood.", "label": 0},
    {"text": "The Great Wall of China is not visible from the Moon with the naked eye.", "label": 0},
    {"text": "A group of owls is called a 'parliament.'", "label": 0},
    {"text": "There are more possible iterations of a game of chess than there are atoms in the known universe.", "label": 0},
    {"text": "Banging your head against a wall burns 150 calories per hour.", "label": 0},
    {"text": "The longest English word without a vowel is 'rhythms.'", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "Pigs have been trained to play video games with their snouts.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Bananas are berries, but strawberries aren't. In botanical terms, berries have seeds on the inside.", "label": 0},
    {"text": "Octopuses have three hearts. Two pump blood to the gills, and one pumps it to the rest of the body.", "label": 0},
    {"text": "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "The longest hiccuping spree lasted 68 years. Charles Osborne hiccuped from 1922 until 1990.", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Penguins can jump up to 6 feet in the air.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Venus rotates in the opposite direction to most planets in our solar system.", "label": 0},
    {"text": "The smell of freshly-cut grass is actually a plant distress call.", "label": 0},
    {"text": "An octopus has three hearts and blue blood.", "label": 0},
    {"text": "The Great Wall of China is not visible from the Moon with the naked eye.", "label": 0},
    {"text": "A group of owls is called a 'parliament.'", "label": 0},
    {"text": "There are more possible iterations of a game of chess than there are atoms in the known universe.", "label": 0},
    {"text": "Banging your head against a wall burns 150 calories per hour.", "label": 0},
    {"text": "The longest English word without a vowel is 'rhythms.'", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "Pigs have been trained to play video games with their snouts.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Bananas are berries, but strawberries aren't. In botanical terms, berries have seeds on the inside.", "label": 0},
    {"text": "Octopuses have three hearts. Two pump blood to the gills, and one pumps it to the rest of the body.", "label": 0},
    {"text": "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "The longest hiccuping spree lasted 68 years. Charles Osborne hiccuped from 1922 until 1990.", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Penguins can jump up to 6 feet in the air.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Venus rotates in the opposite direction to most planets in our solar system.", "label": 0},
    {"text": "The smell of freshly-cut grass is actually a plant distress call.", "label": 0},
    {"text": "An octopus has three hearts and blue blood.", "label": 0},
    {"text": "The Great Wall of China is not visible from the Moon with the naked eye.", "label": 0},
    {"text": "A group of owls is called a 'parliament.'", "label": 0},
    {"text": "There are more possible iterations of a game of chess than there are atoms in the known universe.", "label": 0},
    {"text": "Banging your head against a wall burns 150 calories per hour.", "label": 0},
    {"text": "The longest English word without a vowel is 'rhythms.'", "label": 0},
    {"text": "A group of flamingos is called a 'flamboyance.'", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0},
    {"text": "Pigs have been trained to play video games with their snouts.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Bananas are berries, but strawberries aren't. In botanical terms, berries have seeds on the inside.", "label": 0},
    {"text": "Octopuses have three hearts. Two pump blood to the gills, and one pumps it to the rest of the body.", "label": 0},
    {"text": "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old.", "label": 0},
    {"text": "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.", "label": 0},
    {"text": "Cows have best friends and can become stressed when they are separated.", "label": 0},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer. The heat expands the iron, causing the structure to grow.", "label": 0}
]
